/**
 * Kairo — Transaction Data
 * Realistic Indian transaction data for premium banking experience
 */

import { Transaction, TransactionCategory } from '../utils/types';

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 't1',
    merchantName: 'Swiggy',
    category: 'dining',
    type: 'debit',
    amount: 450.50,
    currency: '₹',
    date: new Date(),
    time: '08:24 PM',
    accountSource: 'Platinum Savings',
    status: 'completed',
  },
  {
    id: 't2',
    merchantName: 'Zomato',
    category: 'dining',
    type: 'debit',
    amount: 820.00,
    currency: '₹',
    date: new Date(),
    time: '01:15 PM',
    accountSource: 'Centurion Credit',
    status: 'completed',
  },
  {
    id: 't3',
    merchantName: 'Amazon India',
    category: 'shopping',
    type: 'debit',
    amount: 2450.00,
    currency: '₹',
    date: new Date(Date.now() - 86400000),
    time: '11:45 AM',
    accountSource: 'Centurion Credit',
    status: 'completed',
  },
  {
    id: 't4',
    merchantName: 'Starbucks',
    category: 'dining',
    type: 'debit',
    amount: 380.00,
    currency: '₹',
    date: new Date(Date.now() - 86400000),
    time: '09:10 AM',
    accountSource: 'Platinum Savings',
    status: 'completed',
  },
  {
    id: 't5',
    merchantName: 'Monthly Salary',
    category: 'salary',
    type: 'credit',
    amount: 185000.00,
    currency: '₹',
    date: new Date(Date.now() - 172800000),
    time: '10:00 AM',
    accountSource: 'Platinum Savings',
    status: 'completed',
  },
  {
    id: 't6',
    merchantName: 'Uber',
    category: 'travel',
    type: 'debit',
    amount: 245.00,
    currency: '₹',
    date: new Date(Date.now() - 172800000),
    time: '08:30 PM',
    accountSource: 'Platinum Savings',
    status: 'completed',
  },
  {
    id: 't7',
    merchantName: 'Reliance Digital',
    category: 'shopping',
    type: 'debit',
    amount: 12500.00,
    currency: '₹',
    date: new Date(Date.now() - 259200000),
    time: '04:20 PM',
    accountSource: 'Centurion Credit',
    status: 'completed',
  },
  {
    id: 't8',
    merchantName: 'Netflix Subscription',
    category: 'entertainment',
    type: 'debit',
    amount: 649.00,
    currency: '₹',
    date: new Date(Date.now() - 345600000),
    time: '12:00 AM',
    accountSource: 'Centurion Credit',
    status: 'completed',
  },
  {
    id: 't9',
    merchantName: 'Dividends',
    category: 'investment',
    type: 'credit',
    amount: 1250.00,
    currency: '₹',
    date: new Date(Date.now() - 432000000),
    time: '02:15 PM',
    accountSource: 'Growth Portfolio',
    status: 'completed',
  },
  {
    id: 't10',
    merchantName: 'HP Petrol Pump',
    category: 'fuel',
    type: 'debit',
    amount: 3500.00,
    currency: '₹',
    date: new Date(Date.now() - 518400000),
    time: '06:45 PM',
    accountSource: 'Platinum Savings',
    status: 'completed',
  },
];
